### ISSUE TITLE
Trying to run the examples... getting errors

### ISSUE THREAD

**Issue by nickwan** [piermorel/gramm#11]
Hi all, this toolbox looks great but I'm having trouble just running the examples from the example.m

For example, when I try to evaluate the "Methods for visualizing repeated trajectories" section I get:

Error using t (line 25)
Not enough input arguments.

Error in nanmean (line 7)
N = sum(~isnan(t), dim);

Error in gramm/stat_summary>my_summary (line 150)
        uni_x=nanmean(x);

Error in gramm/stat_summary>@(dd)my_summary(obj,dd,p.Results) (line 108)
obj.geom=vertcat(obj.geom,{@(dd)my_summary(obj,dd,p.Results)});

Error in gramm/draw (line 488)
                                        obj.geom{geom_ind}(draw_data);

Error in gramm/draw (line 52)
            draw(obj(l,c));

I'm running r2014b. Since this toolbox is pretty new to me, I'm not sure what's the problem here. Hoping for some help -- would love to use this.

**Comment by nickwan** [comment]
Here's the code from the section -- it's unchanged from examples.m

%We generate 50 trajectories of length 40, with 3 groups
N=50;
nx=40;
cval={'A' 'B' 'C'};
cind=randi(3,N,1);
c=cval(cind);
x=linspace(0,3,nx);
y=arrayfun(@(c)sin(x*c)+randn(1,nx)/10+x*randn/5,cind,'UniformOutput',false);

clear g
g(1,1)=gramm('x',x,'y',y,'color',c);
g(1,2)=copy(g(1));
g(2,1)=copy(g(1));
g(2,2)=copy(g(1));

g(1,1).geom_point();
g(1,1).set_title('geom_point()');

g(1,2).geom_line();
g(1,2).set_title('geom_line()');

g(2,1).stat_smooth();
g(2,1).set_title('stat_smooth()');


g(2,2).stat_summary();
g(2,2).set_title('stat_summary()');

g.set_title('Visualization of repeated trajectories ');

figure('Position',[100 100 800 550]);
g.draw();

**Comment by iandol** [comment]
Hm, the code you quote is different from the current examples.m code: https://github.com/piermorel/gramm/blob/master/examples.m#L323

Make sure you've pulled the latest version and try running examples.m from beginning to end.  Works fine for me (on 2016a)...

**Comment by piermorel** [comment]
Hello,

@iandol It looks like the multiply signs disappear in code pasted in main text instead of code section, which explains why the line pasted by @nickwan is different. That said, the example should work, I just tested it on a 2014b version. 

@nickwan From the look of your error messages, you get an error in `nanmean()`:
`Error in nanmean (line 7)
N = sum(~isnan(t), dim);`
However Matlab's own `nanmean()` from the statistics toolbox doesn't have this line. So you probably have a different version of `nanmean()` somewhere on your path that doesn't work as it should. Please run
`which nanmean`
and check whether the path that you get is within matlab's own directory... Let me know !

**Comment by nickwan** [comment]
@piermorel, so nanmean.m is located elsewhere for me:

C:\Users\Lab\Documents\MATLAB\spm8\external\fieldtrip\src\nanmean.m

The simple fix for me was to bring all the MATLAB default toolboxes up to the top of the path list.

**Comment by piermorel** [comment]
Glad my diagnosis was correct and you could solve your problem. That said, you should report to the creators of fieldtrip that their nanmean() function doesn't work exactly the same way as Matlab's, which is problematic since by default theirs seem to supersede Matlab's  (see what input causes this problem in gramm using the debugger).

**Comment by iandol** [comment]
I also use Fieldtrip and don't have this problem (you only add the root folder to the path, so most functions in fieldtrip don't pollute the root namespace). This may be a problem with the way SPM uses fieldtrip...
