### ISSUE TITLE
Problem with facet titles when saving figures as eps or changing resolution for export

### ISSUE THREAD

**Issue by froemero** [piermorel/gramm#18]
I used your handy toolbox to remake some plots I previously made in R. I used facet-wrap for displaying relationships between variables block wise.
Everything went well until I exported the figures. In the eps file, the facet titles were suddenly in the middle of the respective facet plots. Using save yielded the same problem, so it's not the export that's causing the trouble. I tried several things and figured out that if I export it as Tiff without changing the resolution, everything is fine. However, the quality of these plots then is not acceptable, so I can't leave it like that, but changing the resolution messes up the title positions. Is there a way to fix/prevent it? 
I first just copied the figure to pate it to the document I worked on, but then it didn't show the transparency, which I need so the regression lines are visible and don't melt into the points, as they have the same color.Here, it would be great if it were possible to change the color of the regression lines generated by stat_glm() (and also set single colors instead of maps for points, though there are workarounds here), but these latter problems are less important. 

Thank you!

Best wishes,

Romy

**Comment by piermorel** [comment]
Hi, thanks for the report

I was just able to reproduce your problem by trying to export as eps the first figure of the example.m file... weird.

At first look it seems to be linked to the opengl renderer being used and how transparency is (not) handled by Matlab in eps: transparency causes the eps export to use a rasterized version of the figure (look into he eps, it's not "real" vector info and is not better than tiff) which messes up the titles.

If you add `set(gcf,'Renderer','Painters')` then the titles will be well placed and the file will be a non rasterized vector file but you lose transparency (which can be restored in your favorite vector editor). 

For me this is fully a Matlab bug (just another one to add to the long list of vector export problems), but thankfully it **can be completely avoided if you export as .svg** (another vector format) instead of .eps. SVG is well supported in all vector drawing editors and is often imported better (in Illustrator for example the SVG figures don't have these weird cut-in-parts legend text, etc.).

For the color issue, now that you can export with transparency this should be better, and if you want to have different geom/stats with different colormaps you can use update(). Look in the examples.m for examples of use, let me know if you have more questions (I'm not fully clear on what you want to do).

**Comment by piermorel** [comment]
I will also add to the documentation that svg is the least painful export format for vector graphics!

**Comment by froemero** [comment]
Hi,

well, unfortunately it didn't do the deal for me. :(
If I export .svg, I have no transparency, and even though I used this render thing, the titles were still at the wrong place. So, maybe changing the color of the regression line and omitting transparency might do the trick, though I actually like the effect it has on the plot, because it also shows nicely the density of similar observations. 
Now I'm still trying to figure out how to change the line color in the stats_glm results using update... Seems not trivial to me, but maybe I'm just not good enough (yet) at doing figures in Matlab.

To specify what I want to do, I attached a figure. This was saved as png, I didn't change the resolution and still the titles are somewhere. Here you can still see the regression line sufficiently well, but in another plot where I use stat_smooth instead, an important part of the figure is covert by the points without transparency. Thus, a way to change the line color for both stat_glm and stat_smooth would be awesome.

![pe_conf](https://cloud.githubusercontent.com/assets/23497654/20346527/cb0a6ab6-abfc-11e6-8f0f-a434e1e33133.png)

**Comment by piermorel** [comment]
Looks like I closed this issue a bit prematurely!

Could you send me the data you plot and the code you use so that I can see if this reproduces here? Using SVG export without changing the render option should at least give you correct title placement.

I didn't understand it before, but I see that you are using the  'alpha' option of geom_point() and geom_line()... And it appears that it is not supported for the export in svg or pdf (only transparent patches like the ones created by stat_glm() are). I'll look into this but I'm not sure I'll be able to do much here: having transparent point and lines is an undocumented feature of Matlab. It seems to be implemented for on-screen display but not vector export, and as long as it's not officially supported by Matlab (maybe it will come in later Matlab versions) it probably won't change. 

The only workaround there is to set the transparency after the export using a vector editing software like Illustrator (and using advanced selection tools like select>same>fill options).

Now to use update for changing the color:
```Matlab
g=gramm(...) %main call
g.set_color_options( ... ) %Look at doc to see how to alter colors (this can be omitted if you want the points to have the default color)
g.geom_point()
g.draw()
g.update() %Here we don't even provide new arguments since we just want to change the color scheme
g.set_color_options( ... ) %Change options in order to get different colors than in the first call
g.stat_glm()
g.draw()
```

**Comment by froemero** [comment]
Hey,

thanks for digging into this!
Ok, here's the Code and the data attached as ZIP...
[timedebug.zip](https://github.com/piermorel/gramm/files/594676/timedebug.zip)

figure('position',[0 0 20 15])
g=gramm('x',(a1.acE*32),'y',a1.sConfidence);
g.geom_point('alpha', 0.1);
g.facet_grid([],a1.block);
g.set_color_options('map', 'matlab')
g.set_names('column','Block','x','OPE','y','Confidence');
g.set_text_options( 'font', 'Times New Roman');
g.stat_glm();
g.geom_hline('yintercept', 0);
set(gcf,'units','centimeters','position',[0 0 20 15])
g.draw();
saveas(gcf, 'PE_Conf.png')
%export_fig('PE_Conf','-eps','-nocrop');

**Comment by froemero** [comment]
And thanks for the code! Managed to make black regression lines now. That's very helpful!
I'll see how the export works without the transparency. Btw. I'm working on a Mac (Sierra) with Matlab 2016a.

**Comment by froemero** [comment]
Ok, if I omit the alpha setting in geom_point, change the color of the regression line using your code and export as svg, it works like a charm. :) Though Gimp seems to change the font when I import it, but that's apparently a Gimp-Problem... Times new roman is not the prettiest font anyway...

Thanks a lot!

**Comment by piermorel** [comment]
Thanks for the data and code.

I get the same issues as you do using the code you provided. I don't really get what is going on, and it seems to depend on how the figure is exported (png using the save as... menu of the figure seems to work, but not the saveas() function (!) ). I probably won't be able to fix the vector export problem, but I'll see if something can be done for the text placement.

Glad that you reached and acceptable solution using differently colored points!  If you want to visualize density when a lot of points are packed, you can also use stat_bin2d().

**Comment by froemero** [comment]
:) Thanks!

![pe_conf](https://cloud.githubusercontent.com/assets/23497654/20350501/7bb84150-ac0f-11e6-9f4f-2c8e4e219113.png)
