### ISSUE TITLE
subset and set_order_options

### ISSUE THREAD

**Issue by FFroehlich** [piermorel/gramm#20]
When I specify a subset and later want to use set_order_options with a manually specified order, I need to specify an ordering of the value after the application of the subset. I would expect that I can order the full set and that the subset is automatically applied to the ordering aswell.

**Comment by piermorel** [comment]
Good catch! 
The problem is that ultimately the subset is no more than a logical array, and from the moment it's applied (pretty early in the code for optimization) gramm has no idea about the non-selected values anymore. As a consequence I doubt I can easily correct that behavior when you change the order by providing *indices* (ex: ```g.set_order_options('color',[1 3 2]```). However, this shouldn't be a problem when the order is provided using *values* of the variables (ex: ```g.set_order_options('color',{'a' 'c' 'b'}```)

Can you try to replace line 55 in private/unique_and_sort.m from
``` warning('Improper ordering values')```
to
```y=y(order(present));```

and let me know if it works ?

**Comment by FFroehlich** [comment]
the script never reaches line 55 as the check in line 42 already fails. 
I tried to replace 
`warning('Improper order array size: using default order');`
by
`        try
            [present,order]=ismember(sortopts,y);
            if sum(present)==length(y)
                y=y(order);
            else
                warning('Improper ordering values')
                y=y(order(present))
            end
        catch
            warning('Improper ordering values')
        end`
but that also fails because ismember only reports the _lowest absolute index_ and the values in y are unfortunately not unique :(

Another thing that was not intuitive to me was the application of `y=sort(y);` in line 38 . This essentially means that every order that I provide has to be relative to that order, which makes any kind of automated ordering quite complicated.

Essentially what I want to achieve is to sort all x values according to their y values in a `geom_bar` plot. Maybe there is an easier way to achieve this?

**Comment by piermorel** [comment]
To each point, in order:
- Indeed, maybe remove that if/else/end starting line 42.
- At that point in the function, values in y **should be** unique, that's what the beginning of the function does.
- This is why I mention providing the order using the *values* of the variable rather than an *index*, because the index corresponds to the index *in the sorted unique values*. Have you looked at the documentation of set_order_options() ?

Could you provide a minimal example and data so that I can easily try things out for what you are trying to do?

**Comment by FFroehlich** [comment]
Unfortunately I never looked at the documentation of set_order_options() itself, but it is now quite clear why I could not achieve the expected behaviour.

what I was trying to do is the following:

https://gist.github.com/FFroehlich/e76e713e201ec243a21490bfebdfd7c7

is there any way to achieve what I am trying to do? Maybe the description in the gramm cheat sheet could be updated to read 

> Categorial variables sorted in ascending order (numeric or alphabetical)

instead of

> Values sorted in ascending order (numeric or alphabetical)

to be more specific what the function is actually doing.

**Comment by piermorel** [comment]
Just checked your example code, a few comments:

-  giving the order using the **values**, as I recommended, works perfectly in the example you gave me. In your example this is:
```Matlab
g(1,2).set_order_options('x',subx(order));
```

- > I was expecting to be able to do g(1,2).set_order_options('y',1)
Y is the only thing that can't be sorted in gramm, as order only makes sense in categorical cases (colors, categorical x, etc), but I see how this could have made sense in a way.

- I chose to have order indices given relative to *sorted* unique values of the variable so that it makes it easier to change the order to what you want. If you have categories 'a','b','c', you know that to get 'b','a','c' you provide [2 1 3], no matter how the categories happen in the actual data.

- If you do want to use the order of appearance in the original data  you can use the option ```set_order_options('x',0)```.  It might also be the best solution for you: just put everything in a table and sort according to y: this way you don't need to do the sorting on the subset etc. Here is your example modified this way:

```Matlab
clear t
t.xx =     {'C','C','C','B','B','B','A','A','A'}';
t.yy =     [ 2 , 1 , 3 , 3 , 2 , 1 , 1 , 3 , 2 ]';
t.type =   [ 1 , 2 , 3 , 1 , 2 , 3 , 1 , 2 , 3 ]';

t=struct2table(t)
t=sortrows(t,'yy')

subset = t.type==1;

g(1,1) = gramm('x',t.xx,'y',t.yy,'subset',subset);
g(1,1).geom_bar();
g(1,2) = gramm('x',t.xx,'y',t.yy,'subset',subset);
g(1,2).geom_bar();
g(1,2).set_order_options('x',0); 
figure
g.draw()
```
 - I'll try to make the documentation clearer on set_order_options(), although there is already an extensive example in examples.m

**Comment by FFroehlich** [comment]
thanks for the feedback, your suggestions sound very reasonable!
I think the documentation in set_order_options() itself is crystal clear, only the documentation in the cheat sheet was a bit misleading for me.
