### ISSUE TITLE
Order with Facet_wrap

### ISSUE THREAD

**Issue by dhb2128** [piermorel/gramm#22]
Hi, I'm a big fan of gramm! 
One thing I was having trouble with, however, was setting the order of the facets with facet_wrap. My groups are often specified by a cell array, but facet_wrap orders them according to their sorted order (as if you had called unique() on them). I know for bar blots with categorical variables you can change the order with g.set_order_options and reset them to the order they were in the input, but is there similar functionality for changing the order of the facets, as you can do with the levels of factors in R?

Thanks!

**Comment by piermorel** [comment]
Hi David, thanks for the feedback.
You can actually reorder facets rows and columns too using `set_order_options()` with the `'column'` and `'row'`options. The documentation of set_order_options() should get improved in the next update, this is not the first issue reminding me that it's a bit lacking!

**Comment by dhb2128** [comment]
Thanks, Pierre. I'm glad that the functionality is already implemented!

Additionally, if I have multiple gramm objects in a single plot like g(1,1) and g(2,1) with the same facet_gridfor rows and columns, is there a way to sync up the axis limits of these objects? i.e. if I have rows A & B in each object and I want both A's to have the same ylims and both B's have the same ylims, but have different limits for A and B is there a way to do this without doing so manually? I don't think the scale options in facet_grid do this, and setting the axe_property only works if you know the limits in advance, which hasn't been the case when I've been using stat_summary.

**Comment by piermorel** [comment]
When you use multiple gramm objects, those are completely independent and don't really "know" about each other (they are just assigned to a different location for the drawing and that's it). That's why they have different limits, separate legends, etc.

In your case, it's maybe possible to get around the limitation without doing everything manually. gramm provides you with the handles of the facet axes ( `g.facet_axes_handles` is public); by retrieving those in both objects and using `hlink = linkprop(wanted_handles_here,'YLim')` you might be able to do what you want (it's used in draw.m on line 891 and later for example). 

Since gramm will probably try to recompute a bunch of things at redraw/resize that hack might not work or not survive, in which case you need to deactivate the redraw callback by having this `g.draw(false)`as your draw call. Let me know if that works: when programming that I remember Matlab being quite peculiar on these things.
