### ISSUE TITLE
Is this a full implementation of ggplot2 or a partial implementation?

### ISSUE THREAD

**Issue by mejliu** [piermorel/gramm#24]
Great work. 
However, i am wondering whether this is a full implementation or a partial implementation of ggplot2 in R? Thanks.

**Comment by piermorel** [comment]
Thanks,

gramm is not really an _implementation_ of ggplot2, as it doesn't aim to reproduce the interface 100%; it is, however, strongly inspired by it. Some of the differences are due to the differences between Matlab and R, others came by choice/simplicity.

In terms of functionality, ggplot2 definitely has more features, especially in terms of customization and flexibility. gramm is however able to do a few things that ggplot2 can't though, and these are quite important for me:
- There is a built-in way to have several gramm plots in a same figure
- gramm is able to plot easily "trajectory-like" data: i.e. x and y can be given as matrices or cells of arrays and some geom_ and stat_ functions act differently in those cases.
- raster plots for neural data

Why, is there a ggplot2 feature you miss very much ? :)
