### ISSUE TITLE
Allow selection for stat_summary and stat_boxplot

### ISSUE THREAD

**Issue by iandol** [piermorel/gramm#5]
Both stat_boxplot and stat_summary force grouping data in x and value data in y. It would be great if we could pass parameters so we could choose if x, y or color etc were used for value and group.

```matlab
g.stat_summary('grouping','color','data','x')
```

**Comment by piermorel** [comment]
Hi Ian, I'm not really sure I understood about what you mean there. When calling the constructor you can provide different groups for color and x, something like that for example.

`xval={'A' 'B'};cval={'I' 'II'};
g=gramm('x',xval(randi([1 2],50,1)),'y',rand(50,1),'color',cval(randi([1 2],50,1)));
g.stat_boxplot('spacing',0.5);
g.draw`

You can exchange which variable to use for x and which one for color in the gramm() call... Is that what you want to do ? The variable given as x dictates the overall position of the boxes on the x axis, and within each of these positions, the boxes get dodged by color so that they stay visible.
The one thing that is currently impossible (and seems like a tough obstacle) is having different grouping and data for different geoms/stats, as ggplot2 is able to do.

**Comment by iandol** [comment]
OK, I think i underestimated gramm. I wanted to do an i.e. geom_jitter then a stat_summary as layers, and assumed my x and y needed to be different, but just trying it now and it works as expected (geom_jitter knows how to handle the case when x=group or x=data). So there is a workaround. And although it would be nice to have the aesthetic flexibility of ggplot2, I understand the difficulty involved...

**Comment by piermorel** [comment]
Glad you managed to do what you wanted. Seeing your contributed repositories, you are probably a fellow neuroscientist, so there are a few additional things you might enjoy in gramm:

For example you can provide spike times for different trials as 'x' data (as a N_trials long cell containing spike times arrays), trial type as 'color' (N_trials long cellstr or array) and use geom_raster('geom','line') to make raster plots or stat_bin() for psth. 

If you have continuous data like LFPs or smoothed spike density estimates you can provide this data as y (with a N_trials long cell containing arrays, or N_trials x N_samples matrix ), give time as x (same format), provide colors or facets (N_trials long cellstr or arrays) and have fun with stat_summary() or geom_line().

**Comment by iandol** [comment]
Indeed, I wondered why you called it 'geom_raster'! Will have a play, thanks again!
