### ISSUE TITLE
Multiple Bar plots

### ISSUE THREAD

**Issue by Globoquadrina** [piermorel/gramm#70]
I hope it is okay that I ask this question here since there was nobody able to help me at Stackoverflow. Though, I love the design of the gramm package, the syntax is completely alien to me. Here is my question that I posted on Stackoverflow, it would be great if somebody could advise me on this and maybe update the HowTo accordingly, as I think, I am not the only one facing that sort of a problem:

I have a dataset (xlsx-file) where TEST_1: A1-A100, TEST_2: B1-B100 and TEST_3: C1-C100. Now, I want to display TEST_1-3 as histograms in the same graphic by using the gramm library for matlab. Here is my code so far:

```
clc
DATA= readtable('DATA.xlsx','Range','A1:C100');
clear g
g(1,1)=gramm('x',DATA);
g(1,1).stat_bin('geom','line','fill','transparent');
g(1,1).set_title('');
g(1,1).set_names('x','Distribution of TEST_1, TEST_2,TEST_3','y','')

figure('Position',[100 100 800 400]);
g.draw();
```

**Comment by piermorel** [comment]
Hi Dennis,

The syntax of gramm is inspired a lot by the ggplot2 package for R, that's why it can seem un-matlab like at the beginning.

To answer your question, gramm is designed around the idea of having data in "long" tables, meaning that a given variable is in a single column, while grouping variables are in other columns. In your case, it would mean that all your data would be in a **single** column, while you would have a second column (with the same length) containing for each data point info about which test it is ('test1', 'test2'...). You will use that second column to specify 'color', or something else in gramm. A lot of matlab's own stats function require data like this these days, and you can see it makes it easier if you have different numbers of datapoint per condition.

To go between a table like you have to a long table, you can try using Matlab's [stack()](https://www.mathworks.com/help/matlab/ref/stack.html?s_tid=doc_ta) function.
