### ISSUE TITLE
Error Plotting Outliers with stat_boxplot

### ISSUE THREAD

**Issue by rjhubbard88** [piermorel/gramm#86]
I ran into an error when plotting a boxplot with multiple conditions to plot.

> Error using plot
>Vectors must be the same length.
>
>Error in gramm/stat_boxplot>my_boxplot (line 140)
>obj.results.stat_boxplot{obj.result_ind,1}.outliers_handle=plot(boxmid(outliersx),outliersy,'o','MarkerEdgeColor','none','MarkerFaceColor',draw_data.color);
>
>Error in gramm/stat_boxplot>@(dobj,dd)my_boxplot(dobj,dd,p.Results) (line 24)
>obj.geom=vertcat(obj.geom,{@(dobj,dd)my_boxplot(dobj,dd,p.Results)});
>
>Error in gramm/draw (line 548)
>                                        obj.geom{geom_ind}(obj,draw_data);
>
>Error in CLOC_DA_gramm_plotting (line 79)
>g.draw()

The error arises because the 'outliersx' and 'outliersy' are not defined properly - namely, 'outliersy' becomes a matrix instead of a vector when there are outliers in multiple conditions.

This is easily solved by changing stat_boxplot.m, like 81, to:

`outliersy=[outliersy; ysel(sel_outlier)'];`

Hope that's helpful!

**Comment by piermorel** [comment]
Hi, thanks for your feedback !

I can't reproduce your issue here, for example boxplots with outliers work well in `examples.m`  (block after line 702). 

It's probably due to the way your input is formatted and I don't want to use a too ad-hoc fix, could you post a minimal working example so that I can see what happens ?
