### ISSUE TITLE
Modifying the legend of a plot

### ISSUE THREAD

**Issue by annguyen42** [piermorel/gramm#99]
Hello,

In your example with cars, how would you modify the text in the legend?
Meaning, under "# Cyl", instead of having "4 6 8", I would replace by "A B C".

With R I saw [here](https://www.datanovia.com/en/blog/ggplot-legend-title-position-and-labels/) that it was 
`# Edit legend title and labels
p + scale_fill_discrete(name = "Dose", labels = c("A", "B", "C"))`
What is the corresponding code for matlab?

Thank you for your help

**Comment by piermorel** [comment]
Hi @annguyen42 ,

In gramm the contents the legend simply correspond to provided data, so if you provide a cell array containing A B C instead of 4 6 8 it will modify the legend accordingly. For a more direct modification, all graphic objects created by gramm are accessible, so you can do things like this : `g.legend_axe_handle.Children(1).String='C'`which could be automated if needed.

**Comment by annguyen42** [comment]
I am sorry but I am getting 
`g.legend_axe_handle.Children(1).String='C';
Invalid or deleted object.`
Also when looking in the g variable, `Children` do not seems to exist?

What am I missing in my matlab script?

Thank you for your help.

**Comment by piermorel** [comment]
`g` is the gramm object created in the first examples of `examples.m` It should contain `legend_axe_handle` only once `g.draw()`has been called and the figure is still opened, sorry for not indicating it earlier. Depending on your Matlab version, how you access objects in the axes handle could change.

**Comment by annguyen42** [comment]
Thank you so much, it works perfectly. I do have access either through the command line and the guy.
